#this is comment
print("hello world!")
print("my first python code")
print("this is my new laptop lenovo loq :)")
print("thank you")
print("doing hackerrank question")
print("doing hackerrank question")
print("rest")
print("part in hackathon")
print("part in hackathon")
print("rest")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")
print("rest for paper")

